version: "3.7"
services:

  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak_demo
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8890:8890"
    depends_on:
      - postgres_keycloak_demo
    networks:
      - keycloak_demo_dev_network

  postgres_keycloak_demo:
    image: postgres:14.2
    command: postgres -c 'max_connections=200'
    volumes:
    -  ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: "exit 0"
    ports:
      - '5436:5432'
    networks:
      - keycloak_demo_dev_network
volumes:
  postgres_keycloak_demo:
networks:
  keycloak_demo_dev_network:
    driver: bridge