version: '3.7'
services:
  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    hostname: keycloak-server
    command:
      - start-dev
    environment:
      KC_DB: postgres
      KC_DB_URI_HOST: postgres_keycloak_demo
      KC_DB_PASSWORD: password12345
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8081"
    networks:
      - ${GLOBAL_NETWORK:-keycloak}
  postgres_keycloak_demo:
    image: postgres:15
    command:
      - postgres -c 'max_connections=280'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password12345
    healthcheck:
      test: "exit 0"
    ports:
      - "5436:5432"
    networks:
     - ${GLOBAL_NETWORK:-keycloak}
