version: '3.7'
services:
  postgres_db_keycloak:
    image: postgres:latest
    container_name: postgres_db_keycloak
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data

  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    hostname: keycloak-server
    ports:
      - "9091:9091"
    depends_on:
      - postgres_db_keycloak # This line ensures that the database starts first
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
      - "JAVA_OPTS=-Djboss.http.port=9091"
      - "DB_VENDOR=POSTGRES"
      - "DB_ADDR=postgres_db_keycloak" # Use the container name as the host name
      - "DB_DATABASE=keycloak"
      - "DB_USER=keycloak"
      - "DB_SCHEMA=keycloak"
      - "DB_PASSWORD=keycloak"
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev", "--http-port=9091", "--db=postgres", "-Dkeycloak.profile.feature.scripts=enabled" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/auth/realms/master" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s


volumes:
  keycloak_postgres_data:
