version: '3.7'

networks:
  application:

services:
  postgres_db_keycloak:
    image: postgres:${POSTGRES_VERSION:-latest}
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=keycloak"
    ports:
      - '5432:5432'
    volumes:
      - "./data/db-keycloak.sql:/docker-entrypoint-initdb.d/db-keycloak.sql"
      - "postgres_storage_1:/var/lib/postgresql/data/"
    networks:
      - application

volumes:
  postgres_storage_1:
    driver: local
