version: '3.7'
services:
  postgres_db_keycloak:
    image: postgres:${POSTGRES_VERSION:-latest}
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=keycloakk"
      - "POSTGRES_INITDB_WALDIR=/docker-entrypoint-initdb.d"
    ports:
      - '5432:5432'
    volumes:
      - "postgres_storage_1:/var/lib/postgresql/data/"
      - "./init-scripts:/docker-entrypoint-initdb.d"

    networks:
      - ${GLOBAL_NETWORK:-db}
  postgres_db_elastic_query_service:
    image: postgres:${POSTGRES_VERSION:-latest}
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"
    ports:
      - '5433:5432'
    volumes:
      - "./data/db-elastic-query-service.sql:/docker-entrypoint-initdb.d/db-elastic-query-service.sql"
      - "postgres_storage_2:/var/lib/postgresql/data/"
    networks:
      - ${GLOBAL_NETWORK:-db}

networks:
  db:
    driver: bridge


volumes:
  postgres_storage_1:
    driver: local
  postgres_storage_2:
    driver: local
