spring:
  application:
    name: reactive-elastic-query-web-client
  profiles:
    active: reactive_elastic_query_web
  config:
    import: 'configserver:'
  cloud:
    config:
      name: reactive-elastic-query-web-client,config-client
      username: spring_cloud_user
      password: '1234'
      uri: http://localhost:8888




#spring:
#  application:
#    name: reactive-elastic-query-web-client
#  profiles:
#    active: reactive_elastic_query_web
#  cloud:
#    config:
#      name: reactive-elastic-query-web-client,config-client
#      uri: http://localhost:8888
#      username: spring_cloud_user
#      password: '1234'